title: "Our Services"

HeadingDC: "ğŸ”¬ Discovery"
s3Discovery: "User Researsh"
s4Discovery: "Business Goals"
s5Discovery: "Surveys & Feedbacks"


HeadingDG: "ğŸ“ Design"
s1Design: "Logo & Brand Style Guide"
s2Design: "Design Sprints"
s3Design: "UX/UI Design"
s4Design: "Wireframing"
s5Design: "Prototyping"
s6Design: "Design Workshop"
s7Design: "Motion Design"
s8Design: "Video & Photography"


HeadingDev: "ğŸ–¥ï¸  Development"
s1Development: "Webflow Development"
s2Development: "Web Development"
s3Development: "eCommerce & Product Setup"
s4Development: "Third-Party Apps Integration"


HeadingTest: "ğŸ”§ Usability Testing"
s1Testing: "Test Cases Setup"
s2Testing: "Use Case Testings"
s3Testing: "Heatmap Setup & Accessibility"
s4Testing: "Copywriting & Editing"


HeadingSEO: "ğŸ’¸ SEO & Conversions"
s2SEO: "Marketing Researsh"
s3SEO: "Launch Strategy"
s4SEO: "Site Analytics "
s6SEO: "SEO & Performance"


HeadingMain: "ğŸ¯ Maintenance"
s1Main: "Monthly Analysis"
s2Main: "Website Monitoring"
s3Main: "Insight Tracking"
