title: "Our Services"

HeadingDC: "ğŸ”¬ Discovery"
s1Discovery: "Project Scope"
s2Discovery: "Project Management"
s3Discovery: "Full Website Audit"
s4Discovery: "Branding Sprints"
s5Discovery: "Surveys & Feedbacks"
s6Discovery: "Customers Workshops"


HeadingDG: "ğŸ“ Design"
s1Design: "Logo & Brand Style Guide"
s2Design: "Design Sprints"
s3Design: "UX/UI Design"
s4Design: "Wireframing"
s5Design: "Prototyping"
s6Design: "Design System"
s7Design: "Motion Design"
s8Design: "Video & Photography"


HeadingDev: "ğŸ–¥ï¸  Development"
s1Development: "Webflow Development"
s2Development: "Design Deployment"
s3Development: "eCommerce & Product Setup"
s4Development: "Third-Party Apps Integration"


HeadingTest: "ğŸ”§ Usability Testing"
s1Testing: "Test Cases Setup"
s2Testing: "Use Case Testings"
s3Testing: "Heatmap Setup & Accessibility"
s4Testing: "Copywriting & Editing"


HeadingSEO: "ğŸ’¸ SEO & Conversions"
s1SEO: "Content Strategy"
s2SEO: "Marketing Campaigns"
s3SEO: "Launch Strategy"
s4SEO: "Site Analytics "
s5SEO: "Audience Tracking and Setup"
s6SEO: "SEO & Performance"


HeadingMain: "ğŸ¯ Maintenance"
s1Main: "Monthly Analysis"
s2Main: "Website Monitoring"
s3Main: "Insight Tracking"
s4Main: "Customer Support"
